server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy API + health to backend
  location /api/ {
    proxy_pass http://api:8000;
    proxy_set_header Host $host;
    client_max_body_size 200m;
  }
  location /health {
    proxy_pass http://api:8000;
  }
}
